### ISSUE TITLE
Documentation - what it the difference between `end` and `destroy` for sockets in this library?

### ISSUE THREAD

**Issue by john-privy** [wei-rong-1/node-vsock#1]
It's unclear how they behave and what is different about them.

Thanks!

**Comment by wei-rong-1** [comment]
`end` will execute the socket's `shutdown` operation.
`destroy` will close the socket connection.

> Executing a shutdown operation does not destroy a socket; instead, it just limits its communication capacities according to the operation mode. Executing a closing operation, in turn, ends the connections of a socket (if any), and also closes its file descriptor, finally destroying the socket.
https://www.baeldung.com/cs/sockets-close-vs-shutdown

**Comment by john-privy** [comment]
Great, so `end` maps to `shutdown` and `destroy` maps to `close`, thank you!

**Comment by adaminglehart** [comment]
@wei-rong-1 a followup question here - I see in your example from the README that on the client side, you call `.end()` after you're done sending data, but you _don't_ ever call `.end()` on the server side (it's commented out). Is that the intended usage here? I assumed we need to call `.end` or `.destroy` at some point on the server too, but maybe I misunderstood

**Comment by wei-rong-1** [comment]
@adaminglehart  we don't need to call `.end` on the server if it calls `.end` on the client. There are a few event hooks bonded in the socket which will call `.end` and `.destroy` automatically.

_index.ts_
```
this.on('_data', this.onData)
this.on('_connect', this.onConnect)
this.on('_error', this.onError)
this.on('_shutdown', this.onShutdown)
this.on('end', this.onEnd)
```

**Comment by adaminglehart** [comment]
got it, thank you for your response!
